In [2]:
#16. How to add a border (filled with 0's) around an existing array?
import numpy as np
x = np.zeros((3,3))
x

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [3]:
np.pad(x,pad_width=1,mode="constant",constant_values=1)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [4]:
#17. What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [7]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x = np.diag([1, 2, 3, 4, 5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [10]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern 
x = np.zeros((8,8))
# (odd_rows, even_columns)
x[1::2,::2] = 1
# (even_rows, odd_columns)
x[::2,1::2] = 1
print(x)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


In [11]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [14]:
#21. Create a checkerboard 8x8 matrix using the tile function
list_0_1 = np.array([ [ 0, 1], [ 1, 0] ])
checkerboard = np.tile(list_0_1, ( 8//2, 8//2)) 
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [18]:
#22. Normalize a 5x5 random matrix
import random
z = np.random.random((5,5))
z

array([[ 0.53997938,  0.51368619,  0.3200854 ,  0.01133729,  0.61797895],
       [ 0.15138203,  0.21262133,  0.31683219,  0.78558481,  0.58880287],
       [ 0.97830217,  0.43139683,  0.54291638,  0.75514134,  0.1259606 ],
       [ 0.43556228,  0.79449761,  0.61686059,  0.68719919,  0.80768364],
       [ 0.29261418,  0.72701919,  0.8190627 ,  0.03172574,  0.30359243]])

In [20]:
zmax, zmin = z.max(), z.min()
z = (z - zmin)/(zmax - zmin)
z

array([[ 0.54670247,  0.51951101,  0.3192961 ,  0.        ,  0.62736681],
       [ 0.14482919,  0.20816066,  0.31593174,  0.8006987 ,  0.59719395],
       [ 1.        ,  0.43441034,  0.54973982,  0.76921517,  0.11853927],
       [ 0.43871809,  0.80991599,  0.62621023,  0.69895186,  0.82355251],
       [ 0.29088636,  0.74013226,  0.83532032,  0.021085  ,  0.30223967]])

In [21]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [22]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.randint(1,10,(5,3))
a

array([[5, 8, 6],
       [3, 6, 9],
       [1, 2, 6],
       [7, 1, 7],
       [7, 2, 3]])

In [23]:
b = np.random.randint(1,10,(3,2))
b

array([[4, 9],
       [3, 1],
       [5, 9]])

In [25]:
np.dot(a,b)

array([[ 74, 107],
       [ 75, 114],
       [ 40,  65],
       [ 66, 127],
       [ 49,  92]])

In [33]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
e = np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
e[(3 < e) & (e < 8)] *= -1
e

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

In [46]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [45]:
#27. Consider an integer vector Z, which of these expressions are legal?
Z = np.arange(5)
#Z**Z
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1
# Z<Z>Z ..illegal

In [47]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ -9.22337204e+18])

In [48]:
#29. How to round away from zero a float array ?
t = np.random.uniform(-10,+10,10)
t

array([-9.8287846 ,  7.08810185, -3.96879667, -6.24392092,  8.78262186,
        6.66766647, -3.73911903, -6.33538016, -3.05897158, -3.63623893])

In [49]:
np.copysign(np.ceil(np.abs(t)), t)

array([-10.,   8.,  -4.,  -7.,   9.,   7.,  -4.,  -7.,  -4.,  -4.])

In [52]:
#30. How to find common values between two arrays?
g = np.array([2,3,9,45,32,5,67])
h = np.array([45,23,4,12,67,2])
np.intersect1d(g,h)

array([ 2, 45, 67])