In [1]:
#1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [3]:
#2. Print the numpy version and the configuration
np.__version__

'1.13.3'

In [5]:
#3. Create a null vector of size 10
x = np.zeros(10)
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
#4. How to find the memory size of any array
x.nbytes

80

In [9]:
#5. How to get the documentation of the numpy add function from the command line? 
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [13]:
#6. Create a null vector of size 10 but the fifth value which is 1
y = np.zeros(10)
y[4] = 1
y

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [15]:
#7. Create a vector with values ranging from 10 to 49
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [18]:
#8. Reverse a vector (first element becomes last)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [19]:
#9. Create a 3x3 matrix with values ranging from 0 to 8

np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
indices = np.nonzero([1,2,0,0,4,0])
indices

(array([0, 1, 4]),)

In [23]:
#11. Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [28]:
#12. Create a 3x3x3 array with random values
import random
ran = np.random.random(3*3*3)
ran

array([ 0.40856346,  0.60139088,  0.70735389,  0.27589143,  0.92668703,
        0.59973708,  0.12459982,  0.356106  ,  0.78037278,  0.66242403,
        0.35916681,  0.58844572,  0.70113044,  0.77301074,  0.91514004,
        0.98653945,  0.96878713,  0.94778857,  0.57677406,  0.78785466,
        0.05766248,  0.08758977,  0.39456587,  0.09300425,  0.68500514,
        0.17433343,  0.84277877])

In [35]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
y = np.random.random(10*100)
y_min = y.min()
y_max = y.max()


In [36]:
y_min

0.00056697607765643365

In [37]:
y_max

0.99880602376908156

In [39]:
#14. Create a random vector of size 30 and find the mean value
z = np.random.random(30)

In [40]:
z

array([ 0.37418816,  0.32745847,  0.5238942 ,  0.65365247,  0.93329271,
        0.90255306,  0.2908635 ,  0.90352166,  0.08926407,  0.28029304,
        0.22523088,  0.88431677,  0.21723627,  0.48103266,  0.38352068,
        0.94861271,  0.4122831 ,  0.84222153,  0.28217119,  0.91255351,
        0.50680522,  0.13040547,  0.69258636,  0.22656811,  0.12793732,
        0.90744875,  0.6009744 ,  0.92477647,  0.60715103,  0.185259  ])

In [41]:
z_mean = z.mean()
z_mean

0.52593575782813595

In [63]:
#15. Create a 2d array with 1 on the border and 0 inside
z = np.arange(0,9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
z[0,:] = 1
z[2,:] = 1
z[1,0] = 1
z[1,2] = 1
z[1,1] = 0
z

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])