In [61]:
#61. Find the nearest value from a given value in an array
import numpy as np
array = np.random.random(20)
array
given_value = 50
#diff between the given point and each array element
diff = np.abs(array - given_value)
#nearest will be the one with the min dist btwn
nearest_index = np.argmin(diff)
array[nearest_index]

0.8718039711370883

In [125]:
#62. Considering two arrays with shape (1,3) and (3,1), 
#how to compute their sum using an iterator?
x = np.arange(3).reshape(1,3)
y = np.arange(3).reshape(3,1)
s = 0
for (i,j) in np.nditer([x,y]):
    s = np.add(i,j)
    print(s)

0
1
2
1
2
3
2
3
4


In [126]:
#63. Create an array class that has a name attribute
# class Array:
#     def __new__(self,array,name)
#     def __init__(self,name,x_cord,y_cord):
#         self.name
#         self.x_cord
#         self.y_cord
# class NamedArray(np.ndarray):
#     def __new__(cls, array, name="no name"):
#         obj = np.asarray(array).view(cls)
#         obj.name = name
#         return obj
#     def __array_finalize__(self, obj):
#         if obj is None: return
#         self.info = getattr(obj, 'name', "no name")

# Z = NamedArray(np.arange(10), "range_10")
# print (Z.name)


In [127]:
#64. Consider a given vector, 
#how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
a = np.random.randint(0,10,10)
b = np.random.randint(0,len(a),10)
np.add.at(a, b, 1)

In [5]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


In [128]:
#66. Considering a (w,h,3) image of (dtype=ubyte), 
#compute the number of unique colorsw,h = 16,16
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
n

4

In [141]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?
x = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = x.sum(axis=(-2,-1))
print(sum)

[[54 48 50 61]
 [52 64 80 40]
 [67 55 56 57]]


In [139]:
#68. Considering a one-dimensional vector D, 
#how to compute means of subsets of D using a vector S of same size describing subset indices?
D = np.random.uniform(0,1,100)
S = np.random.randint(0,1,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[ 0.50046797]


In [10]:
#69. How to get the diagonal of a dot product? 
x = np.random.uniform(0,1,(5,5))
y = np.random.uniform(0,1,(5,5))
np.diag(np.dot(x, y))

array([ 1.11326357,  1.60269295,  1.30213843,  1.14415968,  0.93193301])

In [148]:
#70. Consider the vector [1, 2, 3, 4, 5], 
#how to build a new vector with 3 consecutive zeros interleaved between each value?
a = np.array([1,2,3,4,5])
b = 3
c = np.zeros(len(a) + (len(a)-1)*(b))
c[::b+1] = a
c

array([ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
        0.,  0.,  0.,  5.])

In [149]:
#71. Consider an array of dimension (5,5,3), 
#how to mulitply it by an array with dimensions (5,5)?
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


In [13]:
#72. How to swap two rows of an array?
x = np.arange(25).reshape(5,5)
y[[0,1]] = y[[1,0]]
print(y)


[[ 0.49009037  0.87260438  0.26806575  0.43416441  0.99858532]
 [ 0.47486085  0.45927409  0.78451465  0.09245035  0.50486312]
 [ 0.91072883  0.0692115   0.88433196  0.86072846  0.50059189]
 [ 0.07930913  0.44191994  0.89732277  0.6578872   0.99815622]
 [ 0.08646073  0.60790375  0.97742126  0.4712482   0.56373605]]


In [150]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), 
#find the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
G

array([( 5, 28), ( 5, 50), ( 5, 51), ( 5, 52), (12, 63), (12, 71),
       (15, 42), (15, 94), (25, 43), (25, 65), (28, 50), (29, 36),
       (29, 87), (36, 87), (38, 59), (38, 97), (42, 94), (43, 65),
       (46, 68), (46, 85), (51, 52), (54, 73), (54, 92), (59, 97),
       (60, 69), (60, 79), (63, 71), (68, 85), (69, 79), (73, 92)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

In [15]:
#74. Given a sorted array C that corresponds to a bincount, 
#how to produce an array A such that np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [16]:
#75. How to compute averages using a sliding window over an array?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


In [17]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],
#Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [153]:
#77. How to negate a boolean, or to change the sign of a float inplace?
a = np.random.randint(0,2,100)
np.logical_not(a, out=a)
a = np.random.uniform(-1.0,1.0,100)
np.negative(a, out=a)

array([-0.56085576,  0.69030872, -0.41482387, -0.61219547,  0.5368501 ,
       -0.88734006,  0.37706475,  0.92574429, -0.46664783, -0.50502175,
       -0.25300476, -0.97607412, -0.52187913,  0.66627138,  0.99164243,
        0.2095932 ,  0.80257644, -0.62979473,  0.894614  ,  0.86732688,
       -0.02278741, -0.34123403,  0.09843623,  0.80108911,  0.94317365,
        0.61238092, -0.60021426, -0.65232156,  0.17440649,  0.72002549,
        0.99713236,  0.51424121, -0.15856743,  0.04437763,  0.11655027,
        0.88798832,  0.72459095,  0.61645703, -0.3455285 , -0.96098748,
       -0.21828856, -0.52752047, -0.28806773, -0.11801146, -0.99504627,
        0.43808533, -0.72587565,  0.38176917, -0.30591226, -0.03689601,
        0.19197563, -0.09415505,  0.11193157, -0.01005766, -0.79725233,
       -0.30603386,  0.9914768 ,  0.65096518,  0.73313068, -0.8113519 ,
       -0.66705224,  0.94049894,  0.60879683, -0.03723318, -0.02676411,
       -0.93311522,  0.52378181, -0.42829076,  0.36427224,  0.35

In [19]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, 
#how to compute distance from p to each line i (P0[i],P1[i])
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[  6.54537859   5.82058705   1.68295716   0.31672556   4.14254299
   0.23949236   0.70915404   2.78962973  11.88180757  11.30369354]


In [154]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, 
#how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[  8.25624584  10.9188285   11.58194362   3.7650409    2.52825989
   4.61070722  17.31743372   6.44256448   8.25326806   3.59192036]


In [21]:
# #80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and 
# #centered on a given element (pad with a fill value when necessary
# Z = np.random.randint(0,10,(10,10))
# shape = (5,5)
# fill  = 0
# position = (1,1)

# R = np.ones(shape, dtype=Z.dtype)*fill
# P  = np.array(list(position)).astype(int)
# Rs = np.array(list(R.shape)).astype(int)
# Zs = np.array(list(Z.shape)).astype(int)

# R_start = np.zeros((len(shape),)).astype(int)
# R_stop  = np.array(list(shape)).astype(int)
# Z_start = (P-Rs//2)
# Z_stop  = (P+Rs//2)+Rs%2

# R_start = (R_start - np.minimum(Z_start,0)).tolist()
# Z_start = (np.maximum(Z_start,0)).tolist()
# R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
# Z_stop = (np.minimum(Z_stop,Zs)).tolist()

# r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
# z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
# R[r] = Z[z]
# print(Z)
# print(R)

In [22]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], 
#how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]
x = np.arange(1,15,dtype=np.uint32)
y = stride_tricks.as_strided(x,(11,4),(4,4))
y

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

In [155]:
#82. Compute a matrix rank
a = np.random.uniform(0,1,(10,10))
b, c, e = np.linalg.svd(a)
rank = np.sum(c > 1e-10)
rank

10

In [24]:
#83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


In [156]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
x = np.random.randint(0,5,(10,10))
n = 3
a = 1 + (x.shape[0]-3)
b = 1 + (x.shape[1]-3)
z = stride_tricks.as_strided(x, shape=(a, b, n, n), strides=x.strides + x.strides)
z

array([[[[1, 2, 2],
         [1, 2, 0],
         [0, 4, 0]],

        [[2, 2, 1],
         [2, 0, 3],
         [4, 0, 3]],

        [[2, 1, 2],
         [0, 3, 1],
         [0, 3, 4]],

        [[1, 2, 4],
         [3, 1, 0],
         [3, 4, 4]],

        [[2, 4, 1],
         [1, 0, 2],
         [4, 4, 2]],

        [[4, 1, 2],
         [0, 2, 3],
         [4, 2, 4]],

        [[1, 2, 4],
         [2, 3, 0],
         [2, 4, 4]],

        [[2, 4, 3],
         [3, 0, 1],
         [4, 4, 4]]],


       [[[1, 2, 0],
         [0, 4, 0],
         [2, 1, 4]],

        [[2, 0, 3],
         [4, 0, 3],
         [1, 4, 2]],

        [[0, 3, 1],
         [0, 3, 4],
         [4, 2, 4]],

        [[3, 1, 0],
         [3, 4, 4],
         [2, 4, 3]],

        [[1, 0, 2],
         [4, 4, 2],
         [4, 3, 3]],

        [[0, 2, 3],
         [4, 2, 4],
         [3, 3, 3]],

        [[2, 3, 0],
         [2, 4, 4],
         [3, 3, 4]],

        [[3, 0, 1],
         [4, 4, 4],
         [3, 4, 2]]],


    

In [26]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
S

Symetric([[ 3,  9,  8,  7,  6],
          [ 9,  8,  0,  7, 12],
          [ 8,  0,  1, 42,  8],
          [ 7,  7, 42,  1, 14],
          [ 6, 12,  8, 14,  1]])

In [27]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). 
#How to compute the sum of of the p matrix products at once? (result has shape (n,1))
a, b = 10, 20
C = np.ones((a,b,b))
D = np.ones((a,b,1))
S = np.tensordot(C, D, axes=[[0, 2], [0, 1]])
S

array([[ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.],
       [ 200.]])

In [28]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.]])

In [29]:
#88. How to implement the Game of Life using numpy arrays?

In [30]:
#89. How to get the n largest values of an arrayZ = np.arange(10000)
x = np.arange(10)
np.random.shuffle(x)
n = 5
x[np.argpartition(-x,n)[:n]]


array([9, 8, 7, 6, 5])

In [31]:
#90. Given an arbitrary number of vectors, 
#build the cartesian product (every combinations of every item)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

In [32]:
#91. How to create a record array from a regular array?
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

In [33]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

In [34]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B 
#regardless of the order of the elements in B?
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 6 7]


In [35]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


[[0 4 1]
 [2 0 1]
 [3 3 3]
 [0 0 0]
 [1 0 3]
 [0 2 0]
 [4 0 3]
 [0 3 4]
 [4 2 3]
 [0 4 1]]
[[0 4 1]
 [2 0 1]
 [1 0 3]
 [0 2 0]
 [4 0 3]
 [0 3 4]
 [4 2 3]
 [0 4 1]]
[[0 4 1]
 [2 0 1]
 [1 0 3]
 [0 2 0]
 [4 0 3]
 [0 3 4]
 [4 2 3]
 [0 4 1]]


In [36]:
#95. Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [37]:
#96. Given a two dimensional array, how to extract unique rows?
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


In [38]:
#97. Considering 2 vectors A & B, 
#write the einsum equivalent of inner, outer, sum, and mul function
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[ 0.0568931 ,  0.24699688,  0.37821301,  0.15559426,  0.24022708,
         0.35573126,  0.23436773,  0.29593574,  0.33860846,  0.15620967],
       [ 0.02123721,  0.09219966,  0.14118037,  0.05808064,  0.08967261,
         0.13278832,  0.08748542,  0.11046769,  0.12639667,  0.05831036],
       [ 0.01763991,  0.07658227,  0.11726629,  0.04824256,  0.07448326,
         0.11029575,  0.07266655,  0.09175593,  0.10498676,  0.04843336],
       [ 0.00971461,  0.04217522,  0.06458065,  0.02656804,  0.04101926,
         0.06074184,  0.04001877,  0.05053163,  0.05781809,  0.02667312],
       [ 0.0435361 ,  0.18900855,  0.28941859,  0.11906484,  0.18382811,
         0.27221497,  0.17934439,  0.22645785,  0.25911215,  0.11953577],
       [ 0.12882466,  0.55928211,  0.85639853,  0.35231653,  0.54395304,
         0.80549247,  0.53068556,  0.67009577,  0.76672083,  0.35371002],
       [ 0.09788266,  0.42494984,  0.65070277,  0.26769469,  0.41330261,
         0.61202368,  0.40322181,  0.5091475 

In [39]:
#98. Considering a path described by two vectors (X,Y), 
#how to sample it using equidistant samples
# phi = np.arange(0, 10*np.pi, 0.1)
# a = 1
# x = a*phi*np.cos(phi)
# y = a*phi*np.sin(phi)

# dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
# r = np.zeros_like(x)
# r[1:] = np.cumsum(dr)                # integrate path
# r_int = np.linspace(0, r.max(), 200) # regular spaced path
# x_int = np.interp(r_int, r, x)       # integrate path
# y_int = np.interp(r_int, r, y)

In [40]:
#99. Given an integer n and a 2D array X, 
#select from X the rows which can be interpreted as draws from a multinomial distribution 
#with n degrees, i.e., the rows which only contain integers and which sum to n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[ 2.  0.  1.  1.]]


In [ ]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X 
#(i.e., resample the elements of an array with replacement N times, 
#compute the mean of each sample, and then compute percentiles over the means).
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)