In [29]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
import numpy as np
points = np.zeros((10,10),dtype = [("x_cord","f8"),("y_cord","f8")])
x = np.linspace(0,1,10)
y = np.linspace(0,1,10)
points["x_cord"],points["y_cord"] = np.meshgrid(x,y)

In [31]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
a = np.arange(5)
b = X + 0.5
c = 1.0 / np.subtract.outer(a,b)
print(np.linalg.det(c))

-131.916595013


In [32]:
#48. Print the minimum and maximum representable value for each numpy scalar type 
for i in [np.int8, np.int32, np.int64]:
   print(np.iinfo(i).min)
   print(np.iinfo(i).max)
for i in [np.float32, np.float64]:
   print(np.finfo(i).min)
   print(np.finfo(i).max)
 

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
-1.79769313486e+308
1.79769313486e+308


In [35]:
#49. How to print all the values of an array?
#np.set_printoptions(threshold=np.nan)
Z = np.zeros((3,3))
print(Z)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [37]:
#50. How to find the closest value (to a given scalar) in a vector?
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

33


In [48]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
rep = np.zeros((1,3),dtype= [("position",[("x","f8"),("y","f8")]),("color",[("x","f8"),("y","f8")])])
rep

array([[(( 0.,  0.), ( 0.,  0.)), (( 0.,  0.), ( 0.,  0.)),
        (( 0.,  0.), ( 0.,  0.))]],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('x', '<f8'), ('y', '<f8')])])

In [61]:
#52. Consider a random vector with shape (100,2) representing coordinates, 
#find point by point distances
import random
x = np.random.random((10,2))
X,Y = np.atleast_2d(x[:,0], x[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
#D

In [64]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
a = np.arange(10, dtype=np.float32)
a = a.astype(np.int32, copy=False)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [65]:
#54. How to read the following file? 


In [66]:
#55. What is the equivalent of enumerate for numpy arrays?
x = np.arange(1,10)
for index, value in np.ndenumerate(x):
    print(index, value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9


In [67]:
#56. Generate a generic 2D Gaussian-like array
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
G

array([[ 0.36787944,  0.44822088,  0.51979489,  0.57375342,  0.60279818,
         0.60279818,  0.57375342,  0.51979489,  0.44822088,  0.36787944],
       [ 0.44822088,  0.54610814,  0.63331324,  0.69905581,  0.73444367,
         0.73444367,  0.69905581,  0.63331324,  0.54610814,  0.44822088],
       [ 0.51979489,  0.63331324,  0.73444367,  0.81068432,  0.85172308,
         0.85172308,  0.81068432,  0.73444367,  0.63331324,  0.51979489],
       [ 0.57375342,  0.69905581,  0.81068432,  0.89483932,  0.9401382 ,
         0.9401382 ,  0.89483932,  0.81068432,  0.69905581,  0.57375342],
       [ 0.60279818,  0.73444367,  0.85172308,  0.9401382 ,  0.98773022,
         0.98773022,  0.9401382 ,  0.85172308,  0.73444367,  0.60279818],
       [ 0.60279818,  0.73444367,  0.85172308,  0.9401382 ,  0.98773022,
         0.98773022,  0.9401382 ,  0.85172308,  0.73444367,  0.60279818],
       [ 0.57375342,  0.69905581,  0.81068432,  0.89483932,  0.9401382 ,
         0.9401382 ,  0.89483932,  0.81068432

In [69]:
#57. How to randomly place p elements in a 2D array?
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [70]:
#58. Subtract the mean of each row of a matrix

X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.14355548, -0.60843253, -0.20165568,  0.14755055,  0.05556163,
        -0.06340249,  0.26519092,  0.06566385,  0.201975  ,  0.28110423],
       [-0.1178283 ,  0.40457193, -0.22086276,  0.2566804 , -0.06993878,
        -0.3626723 ,  0.20406706,  0.36077674, -0.04412591, -0.41066809],
       [ 0.14625015, -0.12136313, -0.07397896, -0.23390042,  0.41932837,
         0.15965819, -0.11839612,  0.17708939, -0.14471891, -0.20996855],
       [-0.35631107,  0.20970707,  0.45369563,  0.21764281, -0.43993481,
        -0.22458108, -0.07850523, -0.38636471,  0.52477919,  0.0798722 ],
       [-0.0846937 ,  0.09675897,  0.34438484,  0.1334013 , -0.30623261,
         0.19690856, -0.22337626, -0.14718591,  0.27422088, -0.28418607]])

In [101]:
#59. How to sort an array by the nth column?
from numpy import random
x = random.rand(3, 5)
x
x[:,1].argsort()
#np.sort(x,axis=0)

array([1, 0, 2])

In [102]:
#60. How to tell if a given 2D array has null columns?
x = np.arange(0,10).reshape(2,5)
np.any(x,axis = 0).any()

True