In [2]:
#31. How to ignore all numpy warnings (not recommended)?
#defaults = np.seterr(all="ignore")

In [4]:
#32. Is the following expressions true?
import numpy as np
#np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.


nan

In [5]:
np.emath.sqrt(-1)

1j

In [7]:
#Not True

In [9]:
#33. How to get the dates of yesterday, today and tomorrow?
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2023-03-23
2023-03-24
2023-03-25


In [8]:
#34. How to get all the dates corresponding to the month of July 2016?
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [13]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.arange(1,3)
B = np.arange(3,5) 
print(B)

[3 4]


In [16]:
np.add(A,B,out=B)

array([ 7, 10])

In [18]:
np.divide(A,2,out=A)

TypeError: No loop matching the specified signature and casting
was found for ufunc true_divide

In [19]:
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-28, -60])

In [24]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods
c = np.random.randint(1,10,(3,3))
c

array([[3, 1, 6],
       [9, 9, 2],
       [2, 3, 2]])

In [20]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
a = np.zeros((5,5))
a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
a += np.arange(5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [26]:
#38. Consider a generator function that generates 10 integers and use it to build an array

In [27]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

d = np.linspace(0,1,10)
d

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [32]:
#40. Create a random vector of size 10 and sort it 
X = np.random.random(10)
X

array([ 0.43233641,  0.91593633,  0.41069754,  0.69565646,  0.07749914,
        0.57290552,  0.53242522,  0.87602756,  0.58621484,  0.98420028])

In [34]:
X.sort()
X

array([ 0.07749914,  0.41069754,  0.43233641,  0.53242522,  0.57290552,
        0.58621484,  0.69565646,  0.87602756,  0.91593633,  0.98420028])

In [35]:
#41. How to sum a small array faster than np.sum?
s = np.arange(1,10)
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.add.reduce(s)

45

In [38]:
#42. Consider two random array A and B, check if they are equal
A = np.random.randint(0,10,(3,3))
A

array([[7, 6, 3],
       [6, 1, 5],
       [9, 3, 8]])

In [39]:
B = np.random.randint(0,10,(3,3))
B

array([[6, 4, 0],
       [8, 4, 9],
       [8, 5, 8]])

In [40]:
q = np.array_equal(A,B)
q

False

In [41]:
#43. Make an array immutable (read-only)
#(array).flags.writeable = False

In [42]:
#44. Consider a random 10x2 matrix representing cartesian coordinates,
#convert them to polar coordinates

In [43]:
#45. Create random vector of size 10 and replace the maximum value by 0
m = np.random.random(10)
m

array([ 0.37310253,  0.28864439,  0.97512813,  0.94570517,  0.99809879,
        0.52954124,  0.37276282,  0.01548612,  0.2003214 ,  0.95549267])

In [48]:
m.max()

0.99809878987547707

In [49]:
m[m.argmax()] = 0
m

array([ 0.37310253,  0.28864439,  0.97512813,  0.94570517,  0.        ,
        0.52954124,  0.37276282,  0.01548612,  0.2003214 ,  0.95549267])